
#Nombre de la directiva
name: Deploy to server

on: push


jobs: 
  first_job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}


    steps:
     - name: Genera archivo
       
       run: |
        echo "Archivo prueba, hola" >> test.log

     - name: Subir aretfacto 
       uses: actions/upload-artifact@v4
       with: 
        name: archivo-test
        path: test.log
  
  second_job:
    runs-on: ubuntu-latest
    neeeds: test.log

    steps:
     - name: Descargar artefacto 
       uses: actions/download-artifact@v4
       with: 
        name: archivo-test
      
