
#Nombre de la directiva
name: Deploy to server

on: push


jobs: 
  first_job:
    runs-on: ubuntu-latest


    steps:
     - name: Hola Mundo 
      # Para ejecutar cualquier comando se puede usar la directiva run
       run: echo "Hola mundo"
  
  second_job:
    runs-on: ubuntu-latest

    
    steps:
      - name: Hola Mundo 
        run: echo "Hola mundo segundo"


