
#Nombre de la directiva
name: Deploy to server

on: push


jobs: 
  first_job:
    runs-on: ubuntu-latest

    env: 
      NAME: AstroBot

    steps:
     - name: Working dir 
      # Para ejecutar cualquier comando se puede usar la directiva run
       run: echo "Hola $NAME"
       run: ls -la
       
     - name: Action
       uses: actions/checkout@v4

     - name: working dir after actions
       run: ls -al
  
  second_job:

    #Contextos 
    # La abreviatura para utilizar contextos es la siguiente 
    # ${{ context }}
    # En este contexto se le esta diciento al job que solamente se ejecute 
    # Si se la referencia de la rama es main en git hub 
    if: ${{ github.ref == 'refs/heads/main'}}

    # Esta directiva indica que el segundo job necesita del primer job
    # Acepta listas tambien
    needs: first_job
    runs-on: ubuntu-latest

    
    steps:
      - name: Hola Mundo 
        run: echo "Hola mundo segundo"


