name: "Deploy practice"

#Trigger
# Se dispara el workflow cuando se haga el push 
on:
  push:
    branches: ["main"]

jobs:
  deploy-practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"


